CREATE TABLE [dbo].[ciims_messages] (
	[sent_timestamp] datetime, 
	[uuid] varchar(255) NOT NULL UNIQUE, 
	[eventFullTimestamp] varchar(255), 
	[siteId] varchar(255), 
	[POPtime] varchar(255), 
	[zoneId] varchar(255), 
	[eventType] varchar(255), 
	[transmitterId] varchar(255), 
	[acknowledgeDateTime] varchar(255), 
	[responseDispatched] varchar(255), 
	[subcontractorDispatched] varchar(255), 
	[responseReferenceNumberReceived] varchar(255), 
	[responseReferenceNumber] varchar(255), 
	[dispatchDateTime] varchar(255), 
	[arrivalDateTime] varchar(255), 
	[category] varchar(255), 
	[discoveryMethod] varchar(255), 
	[reportedBy] varchar(255), 
	[rootCause] varchar(255), 
	[investigatorRequired] varchar(255), 
	[investigator] varchar(255), 
	[reactions] varchar(max), 
	[response24] varchar(max), 
	[soa_response] varchar(max),
	PRIMARY KEY (uuid)
)