SELECT  OBJ_GRABBER.name, OBJ_GRABBER.parent_id, OBJ_GRABBER.type, OBJ_GRABBER.model, OBJ_GRABBER.firmware, OBJ_GRABBER.ip, 
OBJ_CAM_VMDA.name,
OBJ_CAM_VMDA_DETECTOR.params,
OBJ_CAM_FACECAPTURE.firserver,
OBJ_REGION.id as region_id,
OBJ_REGION.name as region_name

FROM OBJ_GRABBER

FULL JOIN OBJ_CAM
ON OBJ_GRABBER.id = OBJ_CAM.parent_id

FULL JOIN OBJ_CAM_VMDA
ON OBJ_CAM.id = OBJ_CAM_VMDA.parent_id

FULL JOIN OBJ_CAM_VMDA_DETECTOR
ON OBJ_CAM_VMDA.id = OBJ_CAM_VMDA_DETECTOR.parent_id

FULL JOIN OBJ_REGION
ON OBJ_CAM.region_id = OBJ_REGION.id

FULL JOIN OBJ_CAM_FACECAPTURE
ON OBJ_CAM.id = OBJ_CAM_FACECAPTURE.parent_id




